In [1]:
#Importing Ritual
import numpy as np

In [3]:
# Datatypes and Attributes
# Numpy's main datatype is ndarray

a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [15]:
a2 = np.array([[1,2.0,3.0],[4,5,6.0]])
a3 = np.array ([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [16]:
# Numpy attributes
a3.shape

(2, 3, 3)

In [17]:
a2.shape

(2, 3)

In [18]:
#Numpy Dimensions
a3.ndim, a2.ndim

(3, 2)

In [19]:
a2.dtype

dtype('float64')

In [20]:
#Total Number of Elements
a3.size

18

In [22]:
#Type 
type(a2), type(a3)

(numpy.ndarray, numpy.ndarray)

In [24]:
# Regular Numpy Array
all_ones=np.ones((2,3))
all_ones,all_ones.ndim

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 2)

In [25]:
all_ones_3d=np.ones((2,3,4))
all_ones_3d,all_ones_3d.ndim

(array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]),
 3)

In [26]:
all_zeros=np.zeros((2,3))
all_zeros,all_zeros.ndim

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 2)

In [27]:
range_array=np.arange(0,10,2)
range_array,range_array.ndim

(array([0, 2, 4, 6, 8]), 1)

In [28]:
random_array=np.random.randint(0,10,size=(3,5))
random_array,random_array.ndim

(array([[1, 1, 6, 5, 2],
        [8, 3, 6, 2, 6],
        [2, 3, 3, 0, 3]]),
 2)

In [35]:
random_array_3d=np.random.randint(0,10,size=(3,5,4))
random_array_3d,random_array_3d.ndim

(array([[[5, 5, 8, 3],
         [8, 0, 7, 7],
         [1, 1, 4, 4],
         [2, 9, 6, 4],
         [1, 1, 2, 1]],
 
        [[1, 7, 0, 4],
         [6, 9, 4, 6],
         [1, 0, 8, 2],
         [8, 8, 9, 7],
         [4, 5, 1, 8]],
 
        [[0, 8, 7, 3],
         [2, 5, 1, 8],
         [5, 9, 9, 8],
         [1, 9, 4, 4],
         [5, 5, 3, 1]]]),
 3)

In [32]:
random_array_2=np.random.random((5,3,2))
random_array_2,random_array_2.ndim

(array([[[0.2245587 , 0.02855954],
         [0.91756294, 0.99626053],
         [0.257272  , 0.91089106]],
 
        [[0.17735843, 0.45170238],
         [0.97933221, 0.49633284],
         [0.48940114, 0.66372375]],
 
        [[0.96534421, 0.67560576],
         [0.62382479, 0.88289513],
         [0.33693024, 0.10754458]],
 
        [[0.47211725, 0.13936179],
         [0.68931709, 0.05195772],
         [0.09995218, 0.11690365]],
 
        [[0.24627686, 0.05036593],
         [0.68150906, 0.91594204],
         [0.46278598, 0.65826042]]]),
 3)

In [34]:
random_array_2.shape

(5, 3, 2)

In [36]:
random_array_3=np.random.rand(5,3,4)
random_array_3,random_array_3.ndim

(array([[[0.71392893, 0.38304483, 0.52508685, 0.45120873],
         [0.28017996, 0.17109514, 0.08150243, 0.39750649],
         [0.36468466, 0.29159077, 0.79451039, 0.67448586]],
 
        [[0.84602123, 0.72069184, 0.38926327, 0.56386884],
         [0.40219885, 0.2158852 , 0.28763085, 0.60741963],
         [0.00796809, 0.49741033, 0.6454139 , 0.62563156]],
 
        [[0.40833864, 0.4859769 , 0.30931896, 0.64749947],
         [0.4784879 , 0.50289647, 0.69175337, 0.41794454],
         [0.36237673, 0.02571318, 0.19068096, 0.68704303]],
 
        [[0.05602314, 0.81475969, 0.15247435, 0.87153567],
         [0.01251938, 0.72017124, 0.97320043, 0.95241009],
         [0.58048519, 0.91187998, 0.33291014, 0.58679137]],
 
        [[0.99488636, 0.46409274, 0.707754  , 0.66695269],
         [0.81214557, 0.1071598 , 0.41385689, 0.09344676],
         [0.51739916, 0.04124061, 0.06504796, 0.76840018]]]),
 3)

In [2]:
# Random Seed
np.random.seed(3)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

In [4]:
#Unique Elements in an array
np.unique(random_array_4)

array([0, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Aggregation
np.sum(random_array_4)

84

In [4]:
sum(random_array_4)

array([36, 25, 23])

In [6]:
listy_list=np.random.random(10000)
listy_list[:10]

array([0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ,
       0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ])

# Use `sum()` for python data types and use `np.sum()` for Numpy arrays

In [7]:
%timeit sum(listy_list)
%timeit np.sum(listy_list)

2.55 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
26.2 µs ± 480 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
# Standard deviation = a mesaure of how spread out a group of numbers is from mean 
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = Wider range of numbers
# Lower variance = Lower range of numbers
# Standard deviation = sqrt (vairance)
np.std(listy_list), np.var(listy_list), np.sqrt(np.var(listy_list))

(0.2880062741864281, 0.082947613970748, 0.2880062741864281)

In [9]:
a1=np.random.randint(0,10,size=(2,3))

In [10]:
a1

array([[7, 4, 3],
       [5, 0, 5]])

In [15]:
a1.reshape(2,3,1)

array([[[7],
        [4],
        [3]],

       [[5],
        [0],
        [5]]])

In [16]:
# Transpose 
a1.T

array([[7, 5],
       [4, 0],
       [3, 5]])

In [17]:
a1=np.array([2,5,0,3])
a1

array([2, 5, 0, 3])

In [18]:
# Finding min, max using argsort
np.argsort(a1), np.argmin(a1), np.argmax(a1)

(array([2, 0, 3, 1], dtype=int64), 2, 1)